/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentRouteImport } from './routes/content'
import { Route as DeenRouteImport } from './routes/deen'
import { Route as GithubRouteImport } from './routes/github'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as ContentBoardRouteImport } from './routes/content/board'
import { Route as ContentSettingsRouteImport } from './routes/content/settings'
import { Route as ContentTrashRouteImport } from './routes/content/trash'
import { Route as DeenIndexRouteImport } from './routes/deen/index'
import { Route as DeenHistoryRouteImport } from './routes/deen/history'
import { Route as DeenSettingsRouteImport } from './routes/deen/settings'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as NotesTrashRouteImport } from './routes/notes/trash'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const DeenRoute = DeenRouteImport.update({
  id: '/deen',
  path: '/deen',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContentRoute,
} as any)
const ContentBoardRoute = ContentBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ContentRoute,
} as any)
const ContentSettingsRoute = ContentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ContentRoute,
} as any)
const ContentTrashRoute = ContentTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => ContentRoute,
} as any)
const DeenIndexRoute = DeenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeenRoute,
} as any)
const DeenHistoryRoute = DeenHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DeenRoute,
} as any)
const DeenSettingsRoute = DeenSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DeenRoute,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRoute,
} as any)
const NotesTrashRoute = NotesTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => NotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content': typeof ContentRouteWithChildren
  '/deen': typeof DeenRouteWithChildren
  '/github': typeof GithubRoute
  '/notes': typeof NotesRouteWithChildren
  '/content/board': typeof ContentBoardRoute
  '/content/settings': typeof ContentSettingsRoute
  '/content/trash': typeof ContentTrashRoute
  '/deen/history': typeof DeenHistoryRoute
  '/deen/settings': typeof DeenSettingsRoute
  '/notes/trash': typeof NotesTrashRoute
  '/content/': typeof ContentIndexRoute
  '/deen/': typeof DeenIndexRoute
  '/notes/': typeof NotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/github': typeof GithubRoute
  '/content/board': typeof ContentBoardRoute
  '/content/settings': typeof ContentSettingsRoute
  '/content/trash': typeof ContentTrashRoute
  '/deen/history': typeof DeenHistoryRoute
  '/deen/settings': typeof DeenSettingsRoute
  '/notes/trash': typeof NotesTrashRoute
  '/content': typeof ContentIndexRoute
  '/deen': typeof DeenIndexRoute
  '/notes': typeof NotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content': typeof ContentRouteWithChildren
  '/deen': typeof DeenRouteWithChildren
  '/github': typeof GithubRoute
  '/notes': typeof NotesRouteWithChildren
  '/content/board': typeof ContentBoardRoute
  '/content/settings': typeof ContentSettingsRoute
  '/content/trash': typeof ContentTrashRoute
  '/deen/history': typeof DeenHistoryRoute
  '/deen/settings': typeof DeenSettingsRoute
  '/notes/trash': typeof NotesTrashRoute
  '/content/': typeof ContentIndexRoute
  '/deen/': typeof DeenIndexRoute
  '/notes/': typeof NotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content'
    | '/deen'
    | '/github'
    | '/notes'
    | '/content/board'
    | '/content/settings'
    | '/content/trash'
    | '/deen/history'
    | '/deen/settings'
    | '/notes/trash'
    | '/content/'
    | '/deen/'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/github'
    | '/content/board'
    | '/content/settings'
    | '/content/trash'
    | '/deen/history'
    | '/deen/settings'
    | '/notes/trash'
    | '/content'
    | '/deen'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/content'
    | '/deen'
    | '/github'
    | '/notes'
    | '/content/board'
    | '/content/settings'
    | '/content/trash'
    | '/deen/history'
    | '/deen/settings'
    | '/notes/trash'
    | '/content/'
    | '/deen/'
    | '/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentRoute: typeof ContentRouteWithChildren
  DeenRoute: typeof DeenRouteWithChildren
  GithubRoute: typeof GithubRoute
  NotesRoute: typeof NotesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deen': {
      id: '/deen'
      path: '/deen'
      fullPath: '/deen'
      preLoaderRoute: typeof DeenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof ContentRoute
    }
    '/content/board': {
      id: '/content/board'
      path: '/board'
      fullPath: '/content/board'
      preLoaderRoute: typeof ContentBoardRouteImport
      parentRoute: typeof ContentRoute
    }
    '/content/settings': {
      id: '/content/settings'
      path: '/settings'
      fullPath: '/content/settings'
      preLoaderRoute: typeof ContentSettingsRouteImport
      parentRoute: typeof ContentRoute
    }
    '/content/trash': {
      id: '/content/trash'
      path: '/trash'
      fullPath: '/content/trash'
      preLoaderRoute: typeof ContentTrashRouteImport
      parentRoute: typeof ContentRoute
    }
    '/deen/': {
      id: '/deen/'
      path: '/'
      fullPath: '/deen/'
      preLoaderRoute: typeof DeenIndexRouteImport
      parentRoute: typeof DeenRoute
    }
    '/deen/history': {
      id: '/deen/history'
      path: '/history'
      fullPath: '/deen/history'
      preLoaderRoute: typeof DeenHistoryRouteImport
      parentRoute: typeof DeenRoute
    }
    '/deen/settings': {
      id: '/deen/settings'
      path: '/settings'
      fullPath: '/deen/settings'
      preLoaderRoute: typeof DeenSettingsRouteImport
      parentRoute: typeof DeenRoute
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof NotesRoute
    }
    '/notes/trash': {
      id: '/notes/trash'
      path: '/trash'
      fullPath: '/notes/trash'
      preLoaderRoute: typeof NotesTrashRouteImport
      parentRoute: typeof NotesRoute
    }
  }
}

interface ContentRouteChildren {
  ContentBoardRoute: typeof ContentBoardRoute
  ContentSettingsRoute: typeof ContentSettingsRoute
  ContentTrashRoute: typeof ContentTrashRoute
  ContentIndexRoute: typeof ContentIndexRoute
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentBoardRoute: ContentBoardRoute,
  ContentSettingsRoute: ContentSettingsRoute,
  ContentTrashRoute: ContentTrashRoute,
  ContentIndexRoute: ContentIndexRoute,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

interface DeenRouteChildren {
  DeenHistoryRoute: typeof DeenHistoryRoute
  DeenSettingsRoute: typeof DeenSettingsRoute
  DeenIndexRoute: typeof DeenIndexRoute
}

const DeenRouteChildren: DeenRouteChildren = {
  DeenHistoryRoute: DeenHistoryRoute,
  DeenSettingsRoute: DeenSettingsRoute,
  DeenIndexRoute: DeenIndexRoute,
}

const DeenRouteWithChildren = DeenRoute._addFileChildren(DeenRouteChildren)

interface NotesRouteChildren {
  NotesTrashRoute: typeof NotesTrashRoute
  NotesIndexRoute: typeof NotesIndexRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesTrashRoute: NotesTrashRoute,
  NotesIndexRoute: NotesIndexRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentRoute: ContentRouteWithChildren,
  DeenRoute: DeenRouteWithChildren,
  GithubRoute: GithubRoute,
  NotesRoute: NotesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
